Add missing includes
sna_driver.c: In function 'sna_handle_uevents':
sna_driver.c:799:2: error: implicit declaration of function 'fstat' [-Werror=implicit-function-declaration]