Fix build failure when passing --with-builderstring.
If --with-builderstring="foo" is passed to configure (and sna enabled):
  CC     sna_driver.lo
src/sna/sna_driver.c: In function 'sna_init_scrn':
src/sna/sna_driver.c:1023:7: error: token ""foo"" is not valid in preprocessor expressions

Fix the missing defined() around the BUILDER_DESCRIPTION variable.

Signed-off-by: Cyril Brulebois <kibi@debian.org>