uxa: udev integration depends on fstat and sys/stat.h
src/uxa/intel_driver.c: In function 'I830HandleUEvents':
src/uxa/intel_driver.c:738:14: error: storage size of 's' isn't known
src/uxa/intel_driver.c:746:2: error: implicit declaration of function 'fstat' [-Werror=implicit-function-declaration]

Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>